<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.46.0" />
    <PackageReference Include="Google.Protobuf" Version="3.19.0" />
    <PackageReference Include="Grpc.Tools" Version="2.46.0" />
    <Protobuf Include="C:\\Users\\FelipeCF\\Desktop\\Codigos\\Sistemas-distribuidos\\python_grpc\\ProtoBUffer.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
