# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProtoBUffer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ProtoBUffer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ProtoBUffer.proto\".\n\x0c\x44\x61\x64osArquivo\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x02 \x01(\x0c\"\"\n\x0eUploadResposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t2G\n\rUploadService\x12\x36\n\x14ServicoUploadArquivo\x12\r.DadosArquivo\x1a\x0f.UploadRespostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoBUffer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DADOSARQUIVO']._serialized_start=21
  _globals['_DADOSARQUIVO']._serialized_end=67
  _globals['_UPLOADRESPOSTA']._serialized_start=69
  _globals['_UPLOADRESPOSTA']._serialized_end=103
  _globals['_UPLOADSERVICE']._serialized_start=105
  _globals['_UPLOADSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
