# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import teste_pb2 as teste__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in teste_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DandoOiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Falando = channel.unary_unary(
                '/saudando.DandoOi/Falando',
                request_serializer=teste__pb2.OiRequest.SerializeToString,
                response_deserializer=teste__pb2.OiResposta.FromString,
                _registered_method=True)


class DandoOiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Falando(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DandoOiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Falando': grpc.unary_unary_rpc_method_handler(
                    servicer.Falando,
                    request_deserializer=teste__pb2.OiRequest.FromString,
                    response_serializer=teste__pb2.OiResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saudando.DandoOi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saudando.DandoOi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DandoOi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Falando(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saudando.DandoOi/Falando',
            teste__pb2.OiRequest.SerializeToString,
            teste__pb2.OiResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
